dist: trusty
sudo: required
language: node_js
node_js:
- 8
cache: npm
before_install:
- sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev-dev
before_script:
- npm run bootstrap
- npm run lint
- npm run build
after_success: npm run coverage
